### ISSUE TITLE
function parameter(props) destructuring 시점

### ISSUE THREAD

**Issue by milban** [creatrip/culture#1]
https://github.com/creatrip/admin/pull/105#discussion_r448201098
[admin pr](https://github.com/creatrip/admin/pull/105) 중 @fuzes 님께서 제시해주신 의견입니다.

```ts
// parameter 선언 시점에서 destructuring
function inlineDestructuring({ a, b, c }) {
  ...
}
```

```ts
// 함수 내부에서 desturcturing
function innerDestructuring(props) {
  const { a, b, c } = props;
}
```

**Comment by milban** [comment]
@yunseop-kim 
> 코드 컨벤션 논의에 대해서 의견…
> 전자의 경우 (함수 매개변수 안에서 해체 연산자를 쓰는 경우)는 `내가 이 함수에서는 이 변수들만 쓰겠다` 라는 의도를 포함 할 수 있습니다.
> 그러나 후자의 경우는 (props를 매개변수로 받고 함수 내에서 해체 연산자를 쓰는 경우), props가 또 다른데서 쓰일 수도 있다는 여지를 남기게 될 수도 있습니다.
> 함수가 어떻게 구성이 되는지 문맥에 따라 달라질 수 있는 것이기에 사실 이게 개취의 문제 보다는 분명히 구분지을 필요는 있을 듯 하네요.

동의해용. 그런데 `React`에서는 문법 특성상 inline으로 destructuring을 적용하는게 적절하지 않을까요?

**Comment by fuzes** [comment]
> 코드 컨벤션 논의에 대해서 의견…
> 전자의 경우 (함수 매개변수 안에서 해체 연산자를 쓰는 경우)는 `내가 이 함수에서는 이 변수들만 쓰겠다` 라는 의도를 포함 할 수 있습니다.
> 그러나 후자의 경우는 (props를 매개변수로 받고 함수 내에서 해체 연산자를 쓰는 경우), props가 또 다른데서 쓰일 수도 있다는 여지를 남기게 될 수도 있습니다.
> 함수가 어떻게 구성이 되는지 문맥에 따라 달라질 수 있는 것이기에 사실 이게 개취의 문제 보다는 분명히 구분지을 필요는 있을 듯 하네요.

전자의 경우 내가 이 함수에서는 이 변수들만 쓰겟다라는 의미를 부여하고자 한다면 해체 연산자를 쓰는 것보다 각각 다른 매개변수로 전달하는게 더 명확하지 않을까 싶네요

**Comment by yunseop-kim** [comment]
@milban 네, 저도 그런 맥락으로 말씀드린겁니다.

@fuzes 인라인에서 해체 연산자를 쓰는 것은 또 다른 효과를 기대할 수 있는데, 각각 다른 매개변수로 전달하는 경우는 문맥상에서 어떤 객체의 어떤 값을 넘겨받아서 함수가 돌아가는지를 알기가 어렵습니다. 반면 인라인에서 해체 연산자를 쓰는 경우는 어떤 객체에서 해체를 했는지를 알기 때문에 더 문맥을 파악하기가 쉽다는 장점이 있죠.

**Comment by fuzes** [comment]
@yunseop-kim 어떤 객체의 어떤 값을 넘겨받아서 함수가 돌아가는지 알기 어렵게 객체를 전달한다면, 함수에 과한 정보를 전달한 것은 아닌가 고려해볼 필요가 있어보입니다. 함수에 메시지를 전달할 때에는 최소한의 정보만 전달해야 된다고 생각하기 때문에요

**Comment by yunseop-kim** [comment]
@fuzes 제가 전달하고자 하는 메시지는 `문맥을 파악하기가 용이하다`는 점입니다. 과한 정보를 전달하는 것이 좋은 코딩이 아니라는 점은 당연히 동의하지요. ㅎㅎ

**Comment by fuzes** [comment]
@yunseop-kim 문맥을 파악하기가 용이하다라는 점은 사용할 매개변수들을 함수  내부에서 destructing 한다라는 규칙을 정해 놓는다면 아래 방법으로도 충분히 해결이 가능하지 않을까 싶습니다. 이런 규칙이 있다면 윤섭님께서 말씀하신 `내가 이 함수에서는 이 변수들만 쓰겠다` 라는 의도는 충분히 표현할 수 있다고 생각합니다. 이러한 규칙이 있을 때 어떤 것이 더 보기 편한가라는 점에서 개취의 문제라고 이야기 했던 것이고요 ㅎㅎ

**Comment by milban** [comment]
https://github.com/airbnb/javascript#destructuring
airbnb에 따르면 inline이 best고 함수 내부에서 하는에 good이라고 하네용

**Comment by fuzes** [comment]
> https://github.com/airbnb/javascript#destructuring
> airbnb에 따르면 inline이 best고 함수 내부에서 하는에 good이라고 하네용

좋은 자료네용 destructuring관련해서 참고할 만한 자료 에요
https://codeburst.io/es6-destructuring-the-complete-guide-7f842d08b98f
https://github.com/tipjs/javascript-style-guide

**Comment by milban** [comment]
방금 함수 구현하면서 발생한 상황인데요.
`parameteres`에 타입도 지정해야하고 optional도 표현해줘야 하면 inline destructuring이 안되네요;;
그래서 아래와 같이 해야해용.
이거 해결하는 법 아시는 분 계신가요?
```ts
import React, { PropsWithChildren } from 'react';
import { render as rtlRender, RenderOptions } from '@testing-library/react';
import { CombinedState, Store } from 'redux';
import { Provider } from 'react-redux';

interface Options extends RenderOptions {
  initialState?: any;
  store?: Store<CombinedState<any>>;
}

function render(ui: React.ReactElement, options?: Options) {
  const { initialState, store, ...renderOptions } = options;
  function wrapper({ children }: PropsWithChildren<any>) {
    return <Provider store={store}>{children}</Provider>;
  }
  return rtlRender(ui, {
    wrapper,
    ...renderOptions,
  });
}

export * from '@testing-library/react';

export { render };

```

**Comment by yunseop-kim** [comment]
@milban 
`options`가 일단 optional하기 때문에, destruct 하지 못하는건 이상한 일이 아닌듯 합니다.
그래서 준혁님이 그냥 구현한 코드가 그냥 맞는 거 같은데요!

**Comment by milban** [comment]
> @milban
> `options`가 일단 optional하기 때문에, destruct 하지 못하는건 이상한 일이 아닌듯 합니다.
> 그래서 준혁님이 그냥 구현한 코드가 그냥 맞는 거 같은데요!

오... 생각해보니 그렇네요. 👍

**Comment by fuzes** [comment]
그럼 이 이슈에 대한 것은 
```
function getFullName(user) {
  const firstName = user.firstName;
  const lastName = user.lastName;

  return `${firstName} ${lastName}`;
}
```

이 방식의 bad case 만 사용하지 않는다인가요

**Comment by milban** [comment]
@fuzes 결론적으론 그렇게 생각됩니다. :)
