### ISSUE TITLE
culture repo dir 구조

### ISSUE THREAD

**Issue by milban** [creatrip/culture#2]
## 현재 생각중인 dir 구조
```sh
culture
|--README.md
|--code convention
  |--javascript
    |--README.md
  |--typescript
    |--README.md
|--code review
  |--README.md
```
[airbnb](https://github.com/airbnb/javascript)를 참고했습니다.
airbnb는 언어별로 styled guide 레포가 따로 있는데, 우리는 culture 레포에 모든걸 담기로 했으니 dir로 나누어 봤습니다.
언어별로 convention이 따로 있는게 맞는 것 같기도 했구요.

의견 부탁드립니다. :)

**Comment by fuzes** [comment]
좋네요

**Comment by siner308** [comment]
서로를 대하는 자세같은 부분은 code-of-conduct(행동강령) 이라고 표현을 하고있어요
여기에서는 review를 하는 방법에 관한 것이지만, 서로를 존중해야 한다는 목적으로 작성되는 문서라는 점에서 code-of-conduct라는 이름도 참고해주시면 좋을듯합니다

컨트리뷰팅 가이드에 관한 링크 첨부합니다.
https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md
https://github.com/django/django/blob/master/CONTRIBUTING.rst
https://github.com/django/django/blob/master/AUTHORS
https://github.com/twitter/code-of-conduct
